version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend/vw_history.db:/app/vw_history.db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiYmFmMDAyZDJkODUzYmNjOThkMTUyMWU2ZmZiMjY5YmMiLCJ0IjoiYTZmNjU5YzAtZmY0Ny00MTIyLTkwMmItMTE1YzNhNmY2NzljIiwicyI6Ik1XSmlZVFppTldJdE1EQmhNeTAwWVdJd0xXRTJPVGt0T0Rka09EQTVZamsxWVRVeCJ9
    restart: unless-stopped
